spring:
 application:
  name: springboot-keycloak

 security:
  oauth2:
   resourceserver:
    jwt:
     issuer-uri: http://localhost:8080/realms/SpringBootDemoKeyCloak
     jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
 auth:
  converter:
   resource-id: springboot-keycloak-demo-client
   principle-attribute: preferred_username
   
logger:
 level:
  org.springframework.security: DEBUG

server:
 port: '8081'
